-- SQLite
UPDATE CUSTOMERS SET EMAIL = 'carolina@campuscode.com.br' WHERE NAME = 'Carolina';

UPDATE CUSTOMERS SET BIRTHDATE = '1986-06-19' WHERE NAME = 'Josefa'; 

UPDATE CARS SET YEAR= 2019 WHERE NAME = 'Fiat Cronos';

DELETE FROM CARS WHERE NAME = 'Hyundai HB20 1.6';

ALTER TABLE EMPLOYEES RENAME PHONE to PHONE_NUMBER;