-- SQLite
SELECT CA.NAME as 'CARRO', C.NAME as 'CLIENTE', E.NAME as 'FUNCIONARIO'
    FROM LOCATIONS
    JOIN CUSTOMERS AS C ON C.ID = LOCATIONS.CUSTOMER_ID
    JOIN CARS AS CA ON CA.ID = LOCATIONS.CAR_ID
    JOIN EMPLOYEES AS E ON E.ID = LOCATIONS.EMPLOYEE_ID;
    

SELECT COUNT(*) as 'Num. Locacoes' FROM LOCATIONS;

SELECT *, MAX(TOTAL) FROM LOCATIONS;

SELECT *
    FROM LOCATIONS
    WHERE START_DATE BETWEEN '2022-05-20' AND '2022-12-25';