-- SQLite

SELECT name, lastname, email FROM Customers WHERE state = 'SP';

SELECT * FROM CARS WHERE STATUS = 'Liberado';

SELECT * FROM CARS WHERE YEAR = '2016';

SELECT name, P.DESCRIPTION as 'CARGO' 
    FROM EMPLOYEES
    JOIN POSITIONS AS P ON EMPLOYEES.POSITION_ID = P.ID;

SELECT name
    FROM EMPLOYEES
    JOIN LOCATIONS AS L ON L.EMPLOYEE_ID = EMPLOYEES.ID
    GROUP BY name
    HAVING COUNT(L.ID) > 1;

SELECT NAME 
    FROM CUSTOMERS
    JOIN LOCATIONS AS L ON L.CUSTOMER_ID = CUSTOMERS.ID
    GROUP BY NAME
    HAVING COUNT(L.ID) > 1;

SELECT CA.NAME as 'CARRO', C.NAME as 'CLIENTE', E.NAME as 'FUNCIONARIO'
    FROM LOCATIONS
    JOIN CUSTOMERS AS C ON C.ID = LOCATIONS.CUSTOMER_ID
    JOIN CARS AS CA ON CA.ID = LOCATIONS.CAR_ID
    JOIN EMPLOYEES AS E ON E.ID = LOCATIONS.EMPLOYEE_ID;
    

SELECT COUNT(*) as 'Num. Locacoes' FROM LOCATIONS;

SELECT *, MAX(TOTAL) FROM LOCATIONS;

SELECT *
    FROM LOCATIONS
    WHERE START_DATE BETWEEN '2022-05-20' AND '2022-12-25';