-- SQLite
CREATE TABLE CUSTOMERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    LASTNAME TEXT NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ADDRESS TEXT NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    BIRTHDATE DATE NOT NULL
);

CREATE TABLE CAR_MODEL (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MODE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE CAR_BRAND (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL
);

CREATE TABLE POSITIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE EMPLOYEES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    PHONE TEXT NOT NULL,
    CONTRACT_DATE DATE NOT NULL,
    POSITION_ID INTEGER NOT NULL,

    FOREIGN KEY (POSITION_ID) REFERENCES POSITION (ID)
);

CREATE TABLE CARS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    YEAR INTEGER NOT NULL,
    COLOR TEXT NOT NULL,
    KM INTEGER NOT NULL,
    STATUS TEXT NOT NULL,
    BRAND_ID INTEGER NOT NULL,
    MODEL_ID INTEGER NOT NULL,

    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID),
    FOREIGN KEY (MODEL_ID) REFERENCES MODELS(ID)
);

CREATE TABLE LOCATIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    TOTAL INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    CAR_ID INTEGER NOT NULL,
    EMPLOYEE_ID INTEGER NOT NULL,

    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID),
    FOREIGN KEY (CAR_ID) REFERENCES CARS(ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
);